version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
    build_tower:
        docker:
            # replace with your preferred image
            - image: cimg/base:stable
        steps:
            - checkout
            - docker/build:
                path: ./docker/
                image: rpsofttower/tower
                tag: $VERSION
                debug: false
                lint-dockerfile: false
                treat-warnings-as-errors: false
                use-buildkit: false
workflows:
    build_tower:
        jobs:
            - docker/publish:
                tag: $VERSION 
                image: rpsofttower/tower 
                path: ./docker/ 
                use-docker-credentials-store: false 
                deploy: true 
                docker-password: DOCKER_PASSWORD 
                docker-username: DOCKER_USERNAME 
            - docker/publish:
                tag: latest 
                image: rpsofttower/tower 
                path: ./docker/ 
                use-docker-credentials-store: false 
                deploy: true 
                docker-password: DOCKER_PASSWORD 
                docker-username: DOCKER_USERNAME 